version: '3.8'

services:
  redis-node-1:
    image: redis:7.2
    ports:
      - 7001:6379
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--cluster-enabled", "yes", "--port", "6379"]
    networks:
      - redis-cluster-net

  redis-node-2:
    image: redis:7.2
    ports:
      - 7002:6379
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--cluster-enabled", "yes", "--port", "6379"]
    networks:
      - redis-cluster-net

  redis-node-3:
    image: redis:7.2
    ports:
      - 7003:6379
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--cluster-enabled", "yes", "--port", "6379"]
    networks:
      - redis-cluster-net

  redis-node-4:
    image: redis:7.2
    ports:
      - 7004:6379
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--cluster-enabled", "yes", "--port", "6379"]
    networks:
      - redis-cluster-net

  redis-node-5:
    image: redis:7.2
    ports:
      - 7005:6379
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--cluster-enabled", "yes", "--port", "6379"]
    networks:
      - redis-cluster-net

  redis-node-6:
    image: redis:7.2
    ports:
      - 7006:6379
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--cluster-enabled", "yes", "--port", "6379"]
    networks:
      - redis-cluster-net

networks:
  redis-cluster-net:
