version: "3.8"
services:
  redis:
    image: redis:7.2
    container_name: redis7
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--save", "20 1", "--loglevel", "notice"]

volumes:
  redis_data:
    driver: local