%dev.quarkus.http.port = 9083

quarkus.datasource.db-kind = postgresql
quarkus.datasource.username = demo.dev
quarkus.datasource.password = dev2025!
%prod.quarkus.datasource.reactive.url = vertx-reactive:postgresql://localhost:5432/payment

# drop and create the database at startup (use `update` to only update the schema)
quarkus.hibernate-orm.schema-management.strategy = drop-and-create