%dev.quarkus.http.port = 9082

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=user
quarkus.datasource.password=pass
%prod.quarkus.datasource.reactive.url=vertx-reactive:postgresql://localhost:5432/order

# drop and create the database at startup
quarkus.hibernate-orm.database.generation=drop-and-create

# quarkus.hibernate-orm.sql-load-script=no-file
quarkus.hibernate-orm.log.sql=true
# quarkus.datasource.reactive.url=postgresql://localhost:5432/orders

quarkus.grpc.clients.cart.host=localhost
quarkus.grpc.clients.cart.port=9090